<?php
	## =======================================================================
	## extra_formAction_login												
	## =======================================================================
	## uses all required fields in the xml file to determine if the user
	## can be logged in
	## =======================================================================
	function extra_formAction_login($id,$page_id,$params) {
		## all data is checked. so we only need to
		## check if the user already exist and if not register him
		
		## fetch the fields we need to enter into the db
		$structurefile = MATRIX_BASEDIR.'settings/datatypes/extra_form/'.$params['structure'].'.xml';
		if(!file_exists($structurefile)) {
			return array('status'=>false);
		}
		## okay open the form file and parse it
		$ctl_form = new formparser($structurefile);
		$ctl_form->parse();

		## fetch the data from the formfile
		$fields = $ctl_form->getFields();
		
		## prepare the search parameters
		$search_params = '1=1 ';
		foreach($fields as $current_element) {
			$current_value = mysql_real_escape_string($_POST[$current_element['identifier']]);
			$search_params .= 'AND '.$current_element['identifier'].'="'.$current_value.'" ';
		}
		
		if(isset($params['confirmed'])) {
		 	$search_params .= "AND confirmed='1' ";
		 }
		
		## prepare the db connection
		$db = new DB_Sql();
		
		## prepare the target db object module
		$module = mysql_real_escape_string($params['target']);
		
		## here we track which object we manipulate
		$object_id = 0;
		## we need to check if we have an element that matches our unique identifier
		if($search_params != '1=1 ') {
			## for now we only support elements that store their data in the main table
			$query = "SELECT id FROM ".DB_PREFIX.$module." WHERE ".$search_params;
			$result_pointer = $db->query($query);	
			
			if($db->num_rows() > 0) {
				$db->next_record();
				$object_id = $db->Record['id'];		

				## now we need to fetch the objects details
				
				@include_once(ENGINE.'modules/'.$module.'/settings.php');		
				@include_once(ENGINE.'modules/clients/functions/elements.php');

				$object_info = clients_getClientDetail($object_id);

				## we start a session for now
				UserSession::useCookies(true);
				UserSession::useTransSID(false);
				UserSession::start('workmatrix_user');
				
				## make sure we have a id that is generated by us
				if (UserSession::isNew()) {
					UserSession::regenerateId();
				}	
				
				UserSession::set($module.':logged',true);
				UserSession::set($module.':id',$object_id);
				UserSession::set($module.':target',$module);
				UserSession::set($module.':object',$object_info);
				
				return array('status'=>true,'object_id'=>$object_id);
			} 
		}
		
		return array('status'=>false);
	}					
?>